.projenrc.ts
packages/@aws-cdk/aws-service-spec/.gitignore
packages/@aws-cdk/aws-service-spec/.projen/tasks.json

Previously the build paused at the `gzip` command waiting for confirmation to overwrite the existing file.
Also gitignore the unzipped `db.json` file so it doesn't accidentally end up in the repo.

chore(aws-service-spec): don't require confirmation for gzip

---

packages/@aws-cdk/aws-service-spec/package.json
packages/@aws-cdk/service-spec-types/package.json
packages/@cdklabs/tskb/package.json
packages/@cdklabs/typewriter/package.json
projenrc/workspace.ts

Fixes attempt to publish as private package: `402 Payment Required: You must sign up for private packages`
See https://github.com/cdklabs/awscdk-service-spec/actions/runs/5411843113/jobs/9835226797#step:5:36

chore: set npm publish config for released packages

---

.github/workflows/release.yml
.projenrc.ts

Release weekly on a Friday so we can import the latest spec into `aws/aws-cdk` over the weekend.

chore: release weekly

---

packages/@aws-cdk/aws-service-spec/.npmignore
projenrc/aws-cdk-integration-test.ts

This way we can access the information from in downstream packages and don't have to keep the information twice.

fix(aws-service-spec): include .jsiidiffignore in package

---

packages/@aws-cdk/service-spec-sources/src/patches/service-patches/cloudformation.ts
packages/@aws-cdk/service-spec-sources/src/patches/service-patches/index.ts

The Service Team has informed us about the imminent release of a new schema version that contains properties that are only supported by the CCAPI, but not CloudFormation.
This changes patches these properties out when they are published.

fix(service-spec-sources): remove CCAPI only properties

---

.github/workflows/test-aws-cdk-integration.yml
projenrc/aws-cdk-integration-test.ts

This step is not needed anymore since `aws/aws-cdk` is now officially using the new service-spec.
Previously we needed to overwrite the import statement to use the new code.

chore: remove redundant step from integration test setup

---

.github/workflows/test-aws-cdk-integration.yml
projenrc/aws-cdk-integration-test.ts

We currently do not merge PRs that introduce breaking changes into the spec without human intervention.
Many of these breaking changes are on purpose though, to rectify human errors made in the spec in the past. The upshot is that spec updates often don't get merged.
Disable breaking change checks using `jsii-diff`. Egregious breakage will still be caught if it stops `aws-cdk-lib` from compiling.

chore: disable breaking change checking on specs

---

packages/@aws-cdk/service-spec-build/src/import-cloudformation-registry.ts
packages/@aws-cdk/service-spec-build/test/property-conversion.test.ts

If the CloudFormation Registry schema contains a type definition for an typed object type:
```
{
definitions: {
SomeType: {
type: 'object',
},
}
}
```
We would generate an empty type definitino for `SomeType`, instead of treating it as an alias for `{ type: 'json' }`.
The aliasing is more appropriate and compatible with how we traditionally interpreted the legacy spec.
Fixes #

fix: empty type definitions are generated

---

packages/@aws-cdk/service-spec-importers/src/import-resource-spec.ts

The current behavior marks every type as legacy, which is not wrong, but it would be more useful to only mark the unused types as legacy.

chore: remove debug line

---

packages/@aws-cdk/service-spec-importers/src/resource-builder.ts
packages/@aws-cdk/service-spec-importers/test/sam-resources.test.ts

The service had `cloudFormationNamespace = 'AWS::SAM'` instead of `AWS::Serverless`.

fix: SAM service has incorrect CFN metadata

---

.projenrc.ts
packages/@aws-cdk/service-spec-importers/.projen/tasks.json
packages/@aws-cdk/service-spec-importers/README.md
packages/@aws-cdk/service-spec-importers/src/cli/import-db.ts

The previous PR #635  removed the `FullDatabase` from the `service-spec-importer` package, making the CLI effectively useless since it would never import anything.
Fixing this by adding a simple CLI interface for sources.

feat(service-spec-importer): support sources via cli

---

packages/@aws-cdk/service-spec-importers/src/importers/import-resource-spec.ts
packages/@aws-cdk/service-spec-importers/test/sam-spec.test.ts

The apparent contract we didn't implement correctly was that the fields named `Inclusive*ItemTypes` need to be respected, regardless of whether the top-level type includes `List` or not.
So force that behavior.

fix: SAM spec type is wrong for Serverless Function Policies

---

packages/@aws-cdk/service-spec-importers/src/importers/import-cloudformation-registry.ts
packages/@aws-cdk/service-spec-importers/test/double-import.test.ts

Before merging, the CloudFormation registry importer tried to not emit superfluous fields into the db. So it would not emit `required: false` since the default value of `required` is already `false`.
When we started merging, that lack of emitting meant that any existing value of `required: true` would never be overwritten with `required: undefined` (because `undefined` isn't a value!).
Change this to have the importer always emit `requied: true|false`, so we can correctly update the requiredness of this property.
The merging code itself takes care of canonicalizing `required: false` to removing the property from the data structure, after merging.

fix(importers): `required` can never be set to `false`

---

packages/@aws-cdk/aws-service-spec/build/scrutinies.ts
packages/@aws-cdk/service-spec-types/src/types/resource.ts
packages/@aws-cdk/service-spec-types/test/resource.test.ts

We are checking if a property is a policy document in order to decide if it is scrutinizable or  not.
This check used to check if the property type was `json`.
However more complex types can also be used for policy documents.
This PR changes to check to test if  `json` is assignable to the property type.
In practice this means the property type can be a union that contains the `json` type.

fix(aws-service-spec): scrutinies missing for some policy document properties

---

packages/@aws-cdk/service-spec-importers/schemas/CloudFormationRegistryResource.schema.json
packages/@aws-cdk/service-spec-importers/schemas/SamTemplateSchema.schema.json
packages/@aws-cdk/service-spec-importers/src/types/registry-schema/JsonSchema.ts
packages/@aws-cdk/service-spec-importers/test/cloudformation-registry.test.ts

According to the JSON Schema spec, `{}` should be treated as the `any` type.

fix: handle `{}` types

---

.github/workflows/build.yml
projenrc/diff-db.ts

Makes the currently "failing" build on main pass by bypassing the `diff-db` job that is not useful on `main`.
With this we can actually see if everything is alright on main by looking at the status of the latest commit.

chore: don't diff db on main

---

.projenrc.ts
package.json
packages/@aws-cdk/aws-service-spec/package.json
packages/@aws-cdk/service-spec-importers/package.json
packages/@aws-cdk/service-spec-types/package.json
packages/@cdklabs/tskb/package.json
packages/@cdklabs/typewriter/package.json

This will ensure that all the published NPM packages correctly link back
to this repository. Currently, this information is missing.

chore: set repository url

---

scripts/download.task.js

We always want to download the latest version. The additional headers might encourage hosting services to provide the latest files.
Improves debugging for file downloads.

chore(download-file): set no cache headers & print sha256 of downloaded file

---

packages/@aws-cdk/aws-service-spec/build/patches/service-patches/index.ts
packages/@aws-cdk/aws-service-spec/build/patches/service-patches/resiliencehub.ts

For ResilienceHub, added AZ, Hardware, Software, and Region into their PolicyMap as keys. We are reverting this because Maven builds fail with JSII in awscdk and since this was the only change to ResilienceHub, the assumption is this caused the build failures.
Fixes #

fix(service-spec): patch old `PolicyMap` definition back in for `ResilienceHub`

---

.projenrc.ts
README.md
packages/@aws-cdk/aws-service-spec/build/full-database.ts
packages/@aws-cdk/service-spec-importers/.projen/tasks.json
packages/@aws-cdk/service-spec-importers/README.md
packages/@aws-cdk/service-spec-importers/schemas/GetAttAllowList.schema.json
packages/@aws-cdk/service-spec-importers/src/db-builder.ts
packages/@aws-cdk/service-spec-importers/src/importers/import-getatt-allowlist.ts
packages/@aws-cdk/service-spec-importers/src/loaders/index.ts
packages/@aws-cdk/service-spec-importers/src/loaders/load-getatt-allowlist.ts
packages/@aws-cdk/service-spec-importers/src/types/getatt-allowlist/getatt-allowlist.ts
packages/@aws-cdk/service-spec-importers/src/types/index.ts
packages/@aws-cdk/service-spec-importers/test/getatt-allowlist.test.ts
sources/CloudFormationGetAttAllowList/README.md
sources/CloudFormationGetAttAllowList/gettatt-allowlist.json

Add an allowlist to mark those properties.
All of the properties in this exception list are both configurable as well as retrievable via `GetAtt`; it would not be correct to classify them as `readOnlyProperties`, hence we have an additional list of attributes that have the same name as configurable properties.
The CloudFormation Registry Schema is intended as a generic Control Plane protocol, usable by any orchestration engine (CloudFormation, Terraform, ...); exactly which properties are `GetAtt`able *in addition* to the `readOnlyProperties` is a
CloudFormation-the-orchestrator-specific detail, and hence is not encoded into the Registry Schema files.
That is why we need a separate list for full fidelity.
CloudFormation is currently not accepting new resources where `GetAtt`-able …

feat: add attributes with same name as properties

---

packages/@aws-cdk/aws-service-spec/build/patches/service-patches/index.ts
packages/@aws-cdk/aws-service-spec/build/patches/service-patches/securitylake.ts

The `Sources` property that is part of `AWS::SecurityLake::Subscriber` resource is being dropped due to errors importing the `Source` type. Since `Sources` is an array of `Source` elements, `Sources` is dropped from the final db. This PR fixes the schema format of `Source` to prevent errors while importing. The database diff below shows that the `Sources` property will be added. This [CR](https://github.com/cdklabs/awscdk-service-spec/pull/1118) shows when the `Sources` property was removed but can be a reference to what we should expect to see in the database diff for `Sources`.

chore: patch for AWS::SecurityLake::Subscriber `Source`

---

packages/@aws-cdk/aws-service-spec/build/patches/service-patches/index.ts
packages/@aws-cdk/aws-service-spec/build/patches/service-patches/quicksight.ts

RefreshConfiguration is marked as optional incorrectly by QuickSight team. Updating it back by a temporary patch until their team fixed it.

chore: patch quicksight dataset property

---

.github/workflows/pr-linter-patch-commit-messages.yaml

Tested in a personal environment and verified that this GHA is working as expected and only invoked when patches are made.

chore: add a PR linter for patches

---

packages/@aws-cdk/aws-service-spec/build/patches/service-patches/index.ts
packages/@aws-cdk/aws-service-spec/build/patches/service-patches/iotfleetwise.ts

Fx the schema for resource AWS::IoTFleetWise::DecoderManifest to remove the reference to non-exist definitions CustomDecodingSignalDecoder, and CustomDecodingNetworkInterface

fix(iotfleetwise): add patch to fix the schema definition of the resource DecoderManifest

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/upgrade.yml
package.json
yarn.lock

Our dependency automation is blocked by a breaking change to GitHub's upload-artifact action. The fix is in the new version of projen. Update the version of projen so that our dependency automation works again.

chore: update projen

---

.projenrc.ts
scripts/download.task.js

Our [feat(sources): update stateful-resources](https://github.com/cdklabs/awscdk-service-spec/pull/1106) PR is currently failing to build:
```console
👾 build » compile » build:db | ts-node build/build-db.ts
FAIL
SyntaxError: Unexpected non-whitespace character after JSON at position 3
```
This happens because the `StatefulResources.json` file got updated with an invalid value. Our workflow updates this with the contents of `StatefulResources.json` coming from [cfn-lint](https://github.com/aws-cloudformation/cfn-lint). However, In https://github.com/aws-cloudformation/cfn-lint/pull/3257, this file was [removed](https://raw.githubusercontent.com/aws-cloudformation/cfn-lint/main/src/cfnlint/data/AdditionalSpecs/StatefulResources.json) (it is now inlined inside the python file that was using …

chore: fail downloading sources on http status code != `200`

---

.projen/deps.json
.projenrc.ts
package.json
packages/@cdklabs/typewriter/src/eslint-rules.ts
packages/@cdklabs/typewriter/src/renderer/typescript.ts
packages/@cdklabs/typewriter/test/comments.test.ts
packages/@cdklabs/typewriter/test/exports.test.ts
packages/@cdklabs/typewriter/test/proxy.test.ts
packages/@cdklabs/typewriter/test/ts-rendering.test.ts
yarn.lock

ESLint has moved most of it's style-related linter rules to a namespace called `@stylistic`.
Update our built-in linter rules to reference those rules in the new package name, and change the public interface to accept arbitrary strings, instead of an enum from a specific set of rules.

fix: most eslint rules have moved to @stylistic

---

packages/@aws-cdk/service-spec-importers/src/importers/import-cloudformation-registry.ts
packages/@aws-cdk/service-spec-importers/test/cloudformation-registry.test.ts

Fixes:
if the CFN schema contains some resource or type that contains a property of type that could not be resolved (like by mistake the type definition does not exist in the schema), now the specs importer failed to continue processing the remaining properties, and types defined in this resource/type. 
This PR is to only skip the property that has issues, and continue importing everything else.

fix(service-spec): skip adding a resource property that could not be resolved

---

packages/@aws-cdk/service-spec-importers/src/cli/diff-db.ts
packages/@aws-cdk/service-spec-importers/src/diff-fmt.ts
packages/@aws-cdk/service-spec-importers/src/printable-tree.ts

We used to only render a pretty diff of a spec database.
Make it possible to diff with an empty DB, which is effectively the same as pretty-printing an entire DB.
Update the printing style a little to add more whitespace in places that feel cramped.

feat: make it possible to print a DB

---

packages/@aws-cdk/aws-service-spec/build/patches/service-patches/batch.ts

Keep the old name of `EksPodProperties` to be `PodProperties`.

fix(batch): add patch to keep the old name of the EksPodProperties type.

---

packages/@aws-cdk/aws-service-spec/build/patches/service-patches/batch.ts

add patch to keep the old name of the Volumes, and EfsVolumeConfiguration types.
This PR deletes the Volume, and EFSVolumeConfiguration types.

fix(batch): add patch to keep the old name of the Volumes, and EfsVolumeConfiguration types

---

sources/CloudFormationGetAttAllowList/gettatt-allowlist.json
sources/CloudFormationResourceSpecification/us-east-1/000_cloudformation/500_IoT1Click_patch_PlacementTemplate_DeviceTemplates.json

iot1click resource got shutdown, and we should stop generating the L1 constructs for this service.
Internal ticket P186779697

fix(iot1click): remove iot1click service resources as it got shut down

---

sources/CloudFormationSchema/us-west-2/aws-rds-globalcluster.json

In a recent schema change, globalEndpoint property was added to readOnlyPorperties
```
"readOnlyProperties" : [ "/properties/GlobalEndpoint" ],
```
This caused `GlobalEndpoint` property is being removed from RDS GlobalCluster L1. 
Reverting this change for now to continue the release.

fix: revert adding GlobalClusterEndpoint to readonlyProperty

---

sources/CloudFormationDocumentation/CloudFormationDocumentation.json
sources/CloudFormationSchema/us-east-1/aws-dynamodb-globaltable.json
sources/CloudFormationSchema/us-east-2/aws-dynamodb-globaltable.json
sources/CloudFormationSchema/us-west-2/aws-rds-globalcluster.json

This is a direct removal and not a patch to speed things up and release a version. We most likely don't need a permenant patch for these.

fix: manually patch `AWS::DynamoDB::GlobalTable` and `AWS::RDS::GlobalCluster`

---

packages/@aws-cdk/service-spec-importers/src/importers/import-cloudformation-registry.ts
packages/@aws-cdk/service-spec-importers/src/resource-builder.ts
packages/@aws-cdk/service-spec-importers/test/property-conversion.test.ts

Schema issue summary: there are two ways of defining oneOf/anyOf schema but semantically they mean the same thing:
The property item itself is one of multiple object types, where each type references a definition
The property item is a single type that references a definition, and that definition itself is one of multiple types of definitions.
For example, consider the following two schema:
Scenario one: property item itself is one of multiple object types
```
resource: {
typeName : "AWS::VpcLattice::ResourceConfiguration",
description: "VpcLattice ResourceConfiguration CFN resource",
definitions: {
ResourceConfigurationDefinition: {
oneOf: [
{
additionalProperties: false,
type: 'object',
properties: {
IpResource: {
$ref: '#/definitions/IpResource',
},
},
required: ['IpResource'],
},
{ …
```

fix: correctly generate all properties in oneOf/anyOf schema

---

packages/@aws-cdk/aws-service-spec/package.json

The release workflow is blocked (https://github.com/cdklabs/awscdk-service-spec/actions/runs/13987488911) due to a recent change in the [cdklabs/cdklabs-projen-project-types](https://github.com/cdklabs/cdklabs-projen-project-types/tree/main) dependency ([PR #832](https://github.com/cdklabs/cdklabs-projen-project-types/pull/832)).
Set the devDependency `@aws-cdk/service-spec-importers` of `@aws-cdk/aws-service-spec` to the exact version `0.0.0`, as it is a sibling module within the same monorepo.

fix: update @aws-cdk/aws-service-spec dev dependency

---

packages/@aws-cdk/service-spec-importers/src/importers/import-cloudformation-registry.ts
packages/@aws-cdk/service-spec-importers/src/importers/import-resource-spec.ts
packages/@aws-cdk/service-spec-importers/src/type-manipulation.ts
packages/@aws-cdk/service-spec-importers/test/double-import.test.ts
packages/@aws-cdk/service-spec-importers/test/property-conversion.test.ts
packages/@aws-cdk/service-spec-types/src/types/resource.ts

The type of a property holds a set of `previousTypes`. The reason we hold this type history is because if a CDK Resource property was ever typed as "json", we can never change it to a named type, for backwards compatibility reasons. The L1 code generator for CDK always takes the oldest type that a property advertises and codegens using that.
(In the future it would be possible to generate multiple fields with different types, for example, but we're not currently doing that yet.)
There are two reasons why a property type can change:
- Gradual type refinement (some type that used to be typed as `Json` now gets a named type with accurate field definition)
- Bugfixes (oops! It was never actually an `X` but the schema erroneously advertised it as such)
The reasons for backwards compatibility …

fix(service-spec): treat evolution of json -> string as a bugfix

---

packages/@cdklabs/typewriter/src/renderer/typescript.ts
packages/@cdklabs/typewriter/src/scope.ts
packages/@cdklabs/typewriter/src/statements/statements.ts
packages/@cdklabs/typewriter/test/scope.test.ts

Motivation: to generate a class inside a method. Code like this:
```ts
method.addBody(
new TypeDeclarationStatement(
new ClassType(new DummyScope(), {
name: 'MyClass',
}),
),
);
```
can be used to generate code like this:
```ts
export class OuterClass {
public doSomething(): void {
class MyClass {
}
}
}
```

feat: new type of statement, to wrap type declarations
